import random

class matt:
	quotes = [
		"Just fucking cross your eyes and run at them.",
		"Just cross your eyes it will all be ok",
		"Just bite the pillow.",
		"Guys dont worry the turrets are out of mana",
		"Haxor MAN! ... Injects htmlz into your Source Code",
		"I up smashed this arthas in the face then forward somethinged his something or other"
		"Bomb goes the spaghetti!",
		"Look at that, that's like, sexual. I wanna fuck it.",
		"God damn it, now I've got to go to Narnia to get a diamond",
		"Eat my fucking toad sex slave, bitch. ",
		"Oh we lose! GG... NICK PLEEEEASE!",
		"Okay these berries are kicking my ass right now",
		"That way when she's giving you head your pubes get stuck in her braces.",
		"Girls with braces turn me on, don't ask... it's one of those things.",
		"I love getting ass fucked.",
		"I love sucking dirty rat cock behind shopko every day",
		"GG, fuck you.",
		"Do you know how much tracer hentai I masterbate to when I play her?",
		"If you suck, I'll kick the fuck out of you",
		"ADAM LOOK AT MY PROFILE, I'M A TRAP!",
		"Hentai is a blessing to mankind.",
		"We are fetus!",
		"Some are banging like a biscuit, others look like a deformed rat.",
		"Look at all the jizz in her utersin.",
		"There's so much fucking jizz on her.",
		"Yan-dare.",
		"Gordan Ramsay is pretty hot. He's an attractive man.",
		"I love Shota, male lolis.",
		"I'm really good at unscrewing things. like pickle jars",
		"Have you ever had to pee so bad you could feel it in your eyeballs?",
		"You're nip's slippin out dude, also your blood. That's kinda fucked up, not gonna lie.",
		"Stop being a middleschool basketball kid.",
		"I'm alt f4-ing because I got varion for the sixth time.",
		"Gotta alt f4 in the loading screen to go back in time.",
		"Who's T-Pain?",
		"How dare you spread your food molecules in my area.",
		"I have autism.",
		"I'm a connosisseur of memes.",
		"I'm such a nigger!",
		"Life suckes then you die.",
		"Why did everyone quote: I'm such a nigger?",
		"I'm gay.",
		"Ooooooooh I'm such a fucking nigger faggot, holy shit.",
		"No, this is poop MMR.",
		"Put it together for like ten years, we do all the work, and then it ties to the hybrids. What a sloot.",
		"What the fuck is going on? This game is fucking optimized",
		"BOBBS AWAY!",
		"What a fucking nigger",
		"Nice I have 1 fps! This is awesome. Cool, can't even move. Sweet.",
		"Fuck you nigger.",
		"Why do I even play? This is so fucking stupid. Everyone is so goddamn braindead. This is a waste of my time.",
		"Zuljin go where zuljin go. Zuljin go afk push because this thrall is a god.",
		"Fucking deckard cain up here trying to whack a that shit with his damn stick",
		"Deckard just ran around confused... wait when the fuck was this a skin? It's a furry sylvannas skin. Wow.",
		"Dom you never let me ride on top",
		"That guy was actually full metal retard. There was not a scrap of Neurons left fireing in his brain. I call him dektard.",
		"Oh yeaaaah, hell fuckin yeah. Gazlo MVP, kappa 1 2 3",
		"I re-fucking-fuse",
		"I don't like taking quest, it means I have to do things",
		"Aww fuck my cunt",
		"I press R when they are far.",
		"I press Q when they get close.",
		"We got a fucking ticklestorm flailing pickle \n\"I press R when they are far\n\" raynor",
		"Look at those fucking TITTIES! Jesus fucking christ, god damn it. Big ol' honkers.",
		"Is it unethical to masterbate naked?",
		"I actually wanna play E build azmodan. I wanna go afk and do absolutely nothing.",
		"Maybe I want to be a Loli. What do you have against that?",
		"Dota games are so long that you can enter the game drunk and end the game sober",
		"Are you a nick more so than nick? Making you a nicker?",
		"I kissed a girl and I choked on my sweater!",
		"GUNNER! STOP DRINKING OUT OF THE TOILET!",
		"Good luck world. I'm killing myself.",
		"I think... I'm gonna kill myself",
		"Good game Amon, you fucking faggot. Fucking nerd. You don't have a fucking girlfriend... but neither do I. I don't need no woman.",
		"Unless it's co-op, then all lives matter.",
		"Help! I'm retarded. I can't read!",
		"You fucking twat muffin.",
		"It's not real right? It's not real. It's not real. OH NO IT'S REAL! WHAT THE FUCK?",
		"it's gonna be terrorblade playing fucking farmville facebook game afk farm.",
		"Autism R Us dude, welcome to the jam! I just dusted by accident.",
		"MURDER THEM ALL!",
		"WOW GOOD JOB IT'S ONLY 35 MINUTES WE COULD HAVE WON AT 25 YOU FUCKIN CASUAL.",
		"Oh Dammit. Oh dammit. OH DAMMIT!",
		"Whatever you do, don't be like garret. Absolutely not. Completely useless.",
		"This is fun, I like playing normals",
		"Tinker makes me wanna fucking kill myself and never play this game again.",
		"Listen to me, there's highs and lows when you play video games.",
		"You are goddamn useless garret. I don't even know why, but you are.",
		"Eat my ass faggot. Get mined on, chase me down retard."
		"I'm gay",
		"Yes, eat my ass",
		"I'm a fucking nigger",
		"Sometimes you frisk it up and you just get naked",
		"Kill me dad.",
		"Oh this guy's name is fucking furry nuggies. I just realized I was playing with Furry nuggies!",
		'Matt Bobbs walking around campus with a fucking pillow looking like a glue devourer\n\
"Matt why the hell do you have a pillow?" - Aaron\n\
"Oh, I got kicked out. I sleep in the snow now." - Matt Dobbs',
		'"Dobbs did you know that hitler was a nazi?" - Aaron\n\
"Really? I thought he was a clown. wasn\n\'t it just happy clown day for like five years straight? look at this shit, this is weird, this is very very creepy." - Matt Dobbs',
		'"What did you want me to do?" - Garrett\n\
"Play the video game!" - Matt Dobbs',
		'"Are you ok?" - Aaron\n\
"No I\n\'m not. Help." - Matt Dobbs',
		'"What IS this?" - Matt Dobbs\n\
"Laxative" - Riley\n\
"I DON\n\'T WANT THIS!" - Matt Dobbs',
		'"Matt is that because you love white people" - Aaron\n\
"Yeah, I hate niggers. Kill em all. Kill all niggers, kill all niggers, kill all niggers, kill all niggers, kill all niggers, kill all niggers." - Matt Dobbs']
		
	def random():
		rand = random.SystemRandom()
		n = rand.randint(0, len(matt.quotes) - 1)
		quote = [n, matt.quotes[n]]
		return quote